utea_web/core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import HomepageView, AboutView

urlpatterns = [
    path('', HomepageView.as_view(), name="home"),
    path('about/', AboutView.as_view(), name="about")
]

utea_web/sigle/urls.py
from django.urls import path
from .views import SigleView, SiglaNewView, SiglaEditView, SiglaDeleteView, TipoCreatePopup #, SigleViewTest, SiglaNewViewTest, sigla_new_test, sigla_edit_test
# from sigle import views

app_name = 'sigle'
urlpatterns = [
#    path('sigla/new', views.new_sigla, name='new-sigla'),
#    path('test', SigleViewTest.as_view(), name='sigle-test'),
#    path('testnew', sigla_new_test, name='sigla-new-test'),
#    path('test/<int:pk>', sigla_edit_test, name='sigla-edit-test'),

    path('', SigleView.as_view(), name='sigle-list'),
    path('new', SiglaNewView.as_view(), name='sigla-new'),
    path('<int:pk>', SiglaEditView.as_view(), name='sigla-edit'),
    path('<int:pk>/delete/', SiglaDeleteView.as_view(), name='sigla-delete'),

    path('tipo/new', TipoCreatePopup, name='tipo-new-popup'),
]

utea_web/utea_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from accounts import views as accounts_views


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('core.urls')),
    path('signup/', accounts_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('reset/', auth_views.PasswordResetView.as_view(
            email_template_name = 'password_reset_email.html',
            subject_template_name = 'password_reset_subject.txt',),
        name = 'password-reset'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(
            template_name = 'password_reset_done.html'),
        name = 'password_reset_done'),
    path('utenti/', include('accounts.urls')),
    path('utenti/', include('django.contrib.auth.urls')),
    path('sigle/', include('sigle.urls'))
]

utea_web/templates/base.html
{% load static %}
<!doctype html>
<html lang="it">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Title -->
    <title>{% block title %}UTEA WebHome{% endblock %}</title>
    <link rel="font/ttf" href="{% static 'fonts/PermanentMarker-Regular.ttf' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- FontAwesome CSS - load all styles -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <!-- Application fonts and CSS -->
      <link rel="stylesheet" href="{% static 'css/app.css' %}">
    {% block stylesheet %}{% endblock %}
  </head>

  <body>
    {% block body %}
    <!-- Menu Bar -->
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <div class="container">
        <!-- Logo or Brand : Link to Homepage -->
        <a class="navbar-brand" href="{% url 'home' %}">AROL-UTEA</a>
        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <!-- the collassable menu -->
        <div class="collapse navbar-collapse" id="mainMenu">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="menuModuli" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Moduli</a>
              <div class="dropdown-menu" aria-labelledby="menuModuli">
                <a class="dropdown-item" href="{% url 'sigle:sigle-list'%}">Sigle</a>
<!--
                <a class="dropdown-item" href="{#% url 'sigle:sigle-test'%#}">Sigle(test)</a>
 -->
              </div>
            </li>
          </ul>
          {% if user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true", aria-expanded="false">
                {% if user.is_staff %}<i class="fas fa-user-tie"></i>{% else %}<i class="fas fa-user"></i>{% endif %}
                {{ user.username }}
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                <a class="dropdown-item" href="#">Il mio account</a>
                <a class="dropdown-item" href="#">Cambia password</a>
                {% if user.is_staff %}
                  <a class="dropdown-item" href="/admin">AdminPage</a>
                {% endif %}

                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
              </div>
            </li>
          </ul>
          {% else %}
          <form class="form-inline ml-auto">
            <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a>
            <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
          </form>
          {% endif %}
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
      <ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
      </ol>
        {% block content %}
        {% endblock %}
    </div>
    {% endblock body %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery-3.3.1.min.js'%}"></script>
    <script src="{% static 'js/popper.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    {% block script %}{% endblock %}
  </body>
</html>

utea_web/templates/base_accounts.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'home' %}">AROL-UTEA</a>
    </h1>
    {% block content %}{% endblock %}
  </div>
{% endblock %}