utea_web/core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import HomepageView, AboutView

urlpatterns = [
    path('', HomepageView.as_view(), name="home"),
    path('about/', AboutView.as_view(), name="about")
]

utea_web/sigle/urls.py
from django.urls import path
from .views import SigleView, SiglaNewView, SiglaEditView, SiglaDeleteView, TipoCreatePopup #, SigleViewTest, SiglaNewViewTest, sigla_new_test, sigla_edit_test
# from sigle import views

app_name = 'sigle'
urlpatterns = [
#    path('sigla/new', views.new_sigla, name='new-sigla'),
#    path('test', SigleViewTest.as_view(), name='sigle-test'),
#    path('testnew', sigla_new_test, name='sigla-new-test'),
#    path('test/<int:pk>', sigla_edit_test, name='sigla-edit-test'),

    path('', SigleView.as_view(), name='sigle-list'),
    path('new', SiglaNewView.as_view(), name='sigla-new'),
    path('<int:pk>', SiglaEditView.as_view(), name='sigla-edit'),
    path('<int:pk>/delete/', SiglaDeleteView.as_view(), name='sigla-delete'),

    path('tipo/new', TipoCreatePopup, name='tipo-new-popup'),
]

utea_web/utea_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from accounts import views as accounts_views


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('core.urls')),
    path('signup/', accounts_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('reset/', auth_views.PasswordResetView.as_view(
            email_template_name = 'password_reset_email.html',
            subject_template_name = 'password_reset_subject.txt',),
        name = 'password-reset'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(
            template_name = 'password_reset_done.html'),
        name = 'password_reset_done'),
    path('utenti/', include('accounts.urls')),
    path('utenti/', include('django.contrib.auth.urls')),
    path('sigle/', include('sigle.urls'))
]

utea_web/sigle/models.py
from django.urls import reverse
from django.db import models
from core.models import Lingua

class Tipo_componente(models.Model):
    """
    Tipologia, o meglio famiglia del componente.
    Oltre al tipo viene anche indicato il prefisso utilizzato (max 3 lettere)
    """
    tipo = models.CharField(max_length = 30)
    prefisso = models.CharField(max_length = 3, unique = True)

    def __str__(self):
        return self.tipo

    class Meta:
        verbose_name = "tipologia di componente"
        verbose_name_plural = "tipologie di componenti"



class Sigla(models.Model):
    """
    Contiene la lista delle sigle dei componenti
        (es. B1, SQ6, M2 ...)
    Ad ogni sigla è abbinata la descrizione funzionale
        (es. "Mancanza capsule", "Limite minimo altezza", "Rotazione Teste")
    Ad ogni sigla è abbinato una tipologia di componente (ForeignKey)
        (es. "Fotocellula", "Sensore di prossimità", "Motore")
    """
    sigla = models.CharField(max_length = 5, help_text="Lunghezza massima 5 caratteri")
    descrizione = models.CharField(max_length = 60, help_text="Lunghezza massima 60 caratteri")
    tipo = models.ForeignKey(Tipo_componente, on_delete=models.CASCADE, help_text="Seleziona da lista")

    def __str__(self):
        return self.sigla

    class Meta:
        verbose_name_plural = "sigle"

    def get_absolute_url(self):
        return reverse('sigle:sigla-edit', kwargs={'pk': self.pk})


class Trad_sigla(models.Model):
#    """
#    Tabella delle traduzioni delle descrizioni delle sigle
#    """
    sigla = models.ForeignKey('Sigla', on_delete=models.CASCADE)
    lingua = models.ForeignKey(Lingua, on_delete=models.CASCADE)
    traduzione = models.CharField(max_length = 60)

    def __str__(self):
        return f"{self.lingua}: {self.traduzione}"

    class Meta:
        verbose_name = "traduzione sigla"
        verbose_name_plural = "traduzioni sigle"
        unique_together = ("sigla", "lingua")

utea_web/sigle/forms.py
from django.forms import ModelForm
from django.forms.models import inlineformset_factory
from .models import Sigla, Trad_sigla, Tipo_componente

class SiglaForm(ModelForm):
    class Meta:
        model = Sigla
        fields = ['sigla', 'descrizione', 'tipo']

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        self.fields['tipo'].widget.template_name='sigle/select_add_edit.html'
        


class TraduzioneForm(ModelForm):
    class Meta:
        model = Trad_sigla
        exclude = ()

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args,**kwargs)
    #     self.fields['traduzione'].widget.attrs.update({'class': 'form-control is-valid'})
    #     self.fields['lingua'].widget.attrs.update({'class': 'form-control'})

TraduzioniFormSet = inlineformset_factory(Sigla, Trad_sigla, form=TraduzioneForm, extra=1)

class TipoComponenteForm(ModelForm):
    class Meta:
        model = Tipo_componente
        exclude = ()

utea_web/sigle/views.py
from django.contrib.auth.models import User
# from django.forms import inlineformset_factory
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from extra_views import InlineFormSet, UpdateWithInlinesView, CreateWithInlinesView
from core.models import Lingua
from .models import Sigla, Tipo_componente, Trad_sigla
from .forms import SiglaForm, TraduzioniFormSet, TipoComponenteForm
from django.views.decorators.csrf import csrf_exempt
import json


class SigleView(ListView):
    model = Sigla
    fields = ['sigla', 'descrizione', 'tipo']
    success_url = reverse_lazy('sigle:sigle-list')

class SigleViewTest(ListView):
    model = Sigla
    template_name = 'sigle/sigle_test2.html'
    fields = ['sigla', 'descrizione', 'tipo']
    success_url = reverse_lazy('sigle:sigle-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lingua'] = Lingua.objects.all()
        return context

class TraduzioniInLine(InlineFormSet):
    model = Trad_sigla
    factory_kwargs = {'extra': 1}
    fields = '__all__'

class SiglaNewView(CreateWithInlinesView):
    model = Sigla
    form_class = SiglaForm
    inlines = [TraduzioniInLine, ]
    success_url = reverse_lazy('sigle:sigle-list')


class SiglaEditView(UpdateWithInlinesView):
    model = Sigla
    form_class = SiglaForm
    inlines = [TraduzioniInLine, ]
    #success_url = reverse_lazy('sigle:sigle-list', pk)
    #success_url = reverse_lazy('sigle:sigle-list')

class SiglaDeleteView(DeleteView):
    """ utilizza in automatico il template : sigla_confirm_delete.html """
    model = Sigla
    success_url = "/sigle/"


def TipoCreatePopup(request):
    form = TipoComponenteForm(request.POST or None)
    if form.is_valid():
        instance = form.save()
        return HttpResponse('<script>opener.closePopup(window, "%s", "%s", "#id_tipo");</script>' % (instance.pk, instance))
    return render(request,'sigle/tipo_form.html', {"form" : form})


@csrf_exempt
def get_tipo_id(request):
    if request.is_ajax():
        tipo_tipo = request.GET['tipo_tipo']
        tipo_id = Tipo_componente.objects.get(tipo = tipo_tipo).id
        data = {'tipo_id':tipo_id,}
        return HttpResponse(json.dumps(data), content_type = 'application/json')
    return HttpResponse("/")

utea_web/sigle/templates/sigle/select_add_edit.html
<div class="input-group">
  <div class="input-group-prepend">
    <button class="btn border" type="button"><a href="{{ widget.name }}/new" id='add_{{ widget.name }}' onclick="return showAddPopup(this);"><i class="fas fa-plus"></i></a></button>
  </div>
  <select name="{{ widget.name }}" class="custom-select" {% include "django/forms/widgets/attrs.html" %}>{% for group_name, group_choices, group_index in widget.optgroups %}{% if group_name %}
    <optgroup label="{{ group_name }}">{% endif %}{% for option in group_choices %}
    {% include option.template_name with widget=option %}{% endfor %}{% if group_name %}
    </optgroup>{% endif %}{% endfor %}
  </select>
</div>


<script type="text/javascript">
  function showAddPopup(triggeringLink) {
    var name = triggeringLink.id.replace(/^add_/, '');
    href = triggeringLink.href;
    var win = window.open(href, "Edit", 'height=500,width=800,resizable=yes,scrollbars=yes');
    win.focus();
    return false;
  }
</script>

utea_web/sigle/templates/sigle/sigla_form.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Moduli</a></li>
    <li class="breadcrumb-item">
      <a href="{% url 'sigle:sigle-list' %}">Sigle</a>
    </li>
      <li class="breadcrumb-item active">{% if object %}{{ object }}{% else %}Nuova{% endif %}</li>
{% endblock breadcrumb %}

{% block content %}
<form method="post" novalidate>
  {% csrf_token %}
  {% include 'includes/form.html' %}

  <!-- <a id="edit_tipo" style="cursor: pointer; cursor: hand;"><i class="fas fa-pencil-alt"></i></a> -->

  <button type="submit" class="btn btn-success">Salva</button>

  <hr>
  {% for formset in inlines %}
  <h2>Traduzioni</h2>

  {% include 'includes/formset_table.html' %}
  {% endfor %}

</form>


{% endblock content %}

{% block script %}
<script type="text/javascript">
  function showEditPopup(url) {
    var win = window.open(url, "Edit", 'height=500,width=800,resizable=yes,scrollbars=yes');
    return false;
  }
  function closePopup(win,newID,newRepr,id) {
    $(id).append('<option value=' + newID + ' selected >' + newRepr + '</option>')
    win.close();
  }
</script>


{% endblock script %}

utea_web/sigle/templates/sigle/sigla_list.html
{% extends 'base.html' %}


{% block head_title %}{{ block.super }} Sigle {% endblock head_title%}


{% block content %}

<!-- deleteModal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form name="confirm_delete_form" action="#" method="POST">
        <div class="modal-body">
            {% csrf_token %}
          <p>Sei sicuro di voler cancellare ?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Annulla</button>
          <input type="submit" class="btn btn-primary" value="OK">
        </div>
      </form>
    </div>
  </div>
</div>

<!-- editModal -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form name="sigla_edit_form" action="#" method="POST">
        <div class="modal-body">
            {% csrf_token %}
            {{ edit_form }}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">NO !!</button>
          <input type="submit" class="btn btn-danger" value="Confermo">
        </div>
      </form>
    </div>
  </div>
</div>


<h2>Sigle</h2>
  <table class="table table-sm table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Sigla</th>
        <th scope="col">Descrizione</th>
        <th scope="col">Tipologia</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for sigla in object_list %}
        <tr>
          <th scope="row">{{ sigla.sigla }}</th>
          <td>{{ sigla.descrizione }}</td>
          <td>{{ sigla.tipo.tipo}}</td>
          <td>
            <!--- Button trigger modal -->
            <a class="btn btn-outline-secondary" href="{% url 'sigle:sigla-edit' pk=sigla.pk %}" data-toggle="smodal" data-target="#editModal" data-name={{sigla.sigla}} data-action="#">
              <i class="fas fa-edit" title="Edit"></i>
            </a>
          </td>
          <td>
            <!--- Button trigger modal -->
            <button type="button" class="btn btn-outline-secondary" data-toggle="modal" data-target="#deleteModal" data-name={{sigla.sigla}} data-action="{% url 'sigle:sigla-delete' pk=sigla.pk %}">
              <i class="far fa-trash-alt" title="Delete"></i>
            </button>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <a class="btn btn-sm btn-info" href="{% url 'sigle:sigla-new' %}">Aggiungi Sigla</a>

{% endblock content %}

{% block script %}
{{ block.super }}
  <script>
    $(document).ready(function(){
      $("#deleteModal").on('show.bs.modal', function(event) {
        var button = $(event.relatedTarget) // Button that triggered the modal
        var act = button.data('action') // Extract info from data-* attributes
        var recipient = button.data('name')
        // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
        // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
        var modal = $(this)
        modal.find('.modal-title').text('Delete ' + recipient)
        document['confirm_delete_form'].action = act
      })

      $("#editModal").on('show.bs.modal', function(event) {
        var button = $(event.relatedTarget) // Button that triggered the modal
        var recipient = button.data('name')
        // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
        // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
      })
    })


  </script>
{% endblock script %}

utea_web/sigle/templates/sigle/sigle_test2.html
{% extends 'base.html' %}

{% block title %}
  {{ block.super }} Sigle Test 2
{% endblock title %}

{% block lmenu %}
  <ul>
    {% for lng in lingua %}
    <li>{{ lng.id }}</li>
    {% endfor %}
  </ul>
{% endblock lmenu %}

{% block breadcrumb %}
    <li class="breadcrumb-item"> <a href="{% url 'home' %}">Moduli</a></li>
    <li class="breadcrumb-item active">Sigle(test)</li>
{% endblock breadcrumb %}

{% block content %}

<h2>Sigle</h2>
  <div class="table-responsive">
    <table class="table table-striped table-hover table-sm ">
      <thead class="thead-dark">
        <tr>
          <th scope="col"></th>
          <th scope="col">Sigla</th>
          <th scope="col">Descrizione</th>
          {% for lng in lingua %}
          <th scope="col">{{ lng.id }}</th>
          {% endfor %}
        </tr>
      </thead>
      <tbody>
          {% for sigla in sigla_list %}
          <tr>
            <th><a href="{% url 'sigle:sigla-edit-test' pk=sigla.pk %}"><i class="fas fa-edit"></i></a></th>
            <th scope="row">{{ sigla.sigla }}</th>
            <td>{{ sigla.descrizione }}</td>
              {% for lng in lingua.all %}
                <td>
                {% for trad in sigla.trad_sigla_set.all %}
                    {% if trad.lingua.id == lng.id %}
                      {{ trad.traduzione }}
                    {% endif %}
                {% endfor %}
                </td>
              {% endfor %}
            </tr>
          {% endfor %}
      </tbody>
    </table>
  </div>

  <a class="btn btn-sm btn-info" href="{% url 'sigle:sigla-new-test' %}">Aggiungi Sigla</a>

{% endblock content %}

utea_web/sigle/templates/sigle/tipo_form.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block body %}
<div class="container">
  <form method="post" novalidate id = "tipo-form">
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <input class="btn btn-primary" type="submit" name="some_name" value="Submit">
  </form>
</div>

{% endblock body %}